bls12_381/Cargo.toml

This seems to be somewhat broken when cross compiling from mac (arm) to Mac(x86-64) using zigbuild. We can mitigate this by not cross compiling and running dedicated mac machines for each cpu.
Error message:
```
The following warnings were emitted during compilation:
warning: blst@0.3.11: zig: warning: overriding '-mmacosx-version-min=14.5' option with '-target x86_64-unknown-macosx11.7.1-unknown' [-Woverriding-option]
warning: blst@0.3.11: /var/folders/_9/vnrwx10x7znbs5bqwnvx4tn80000gn/T/assembly-35b5f5.s:1472:1: error: invalid CFI advance_loc expression
warning: blst@0.3.11: .cfi_adjust_cfa_offset 8
warning: blst@0.3.11: ^
warning: blst@0.3.11: /var/folders/_9/vnrwx10x7znbs5bqwnvx4tn80000gn/T/assembly-35b5f5.s:6555:1: error: invalid CFI advance_loc expression
warning: blst@0.3.11: …
```

chore(ci): remove portable flag on blst

---

eip7594/src/prover.rs
kzg_multi_open/src/fk20.rs
kzg_multi_open/src/fk20/naive.rs
kzg_multi_open/src/lib.rs
kzg_multi_open/src/naive.rs

This separates proof generation and computing the evaluation sets from FK20. This is do that we can push it to the caller and then compute the evaluation sets in the reed-solomon crate.

feat: FK20 now only computes proofs

---

bindings/c/src/blob_to_kzg_commitment.rs
bindings/c/src/compute_cells_and_kzg_proofs.rs
bindings/c/src/lib.rs
bindings/c/src/recover_cells_and_kzg_proofs.rs
bindings/c/src/verify_cells_and_kzg_proofs.rs
bindings/c/src/verify_cells_and_kzg_proofs_batch.rs
bindings/java/rust_code/src/lib.rs
bindings/node/__test__/index.spec.ts
bindings/node/index.d.ts
bindings/node/index.js
bindings/node/src/lib.rs
eip7594/benches/benchmark.rs
eip7594/src/lib.rs
eip7594/src/prover.rs
eip7594/src/verifier.rs
eip7594/tests/blob_to_kzg_commitment.rs
eip7594/tests/compute_cells_and_kzg_proofs.rs
eip7594/tests/recover_cells_and_compute_proofs.rs
eip7594/tests/verify_cell_kzg_proof.rs
eip7594/tests/verify_cell_kzg_proof_batch.rs

This PR moves all prover and verifier methods to peerdas context, since downstream callers were combining these two methods anyways.
We will keep the two structures, since they are good for separating resources. But they will not be exposed in the API anymore

chore!: Move all prover and verifier methods to PeerDAS context object

---

eip7594/src/trusted_setup.rs

Removing rust-embed as it does not seem to behave the same way in debug and release mode.
I was not able to pin down the exact issue and or why it happens.

chore: replace rust-embed with include_str!

---

eip7594/benches/benchmark.rs

Noticed this wasn't being benchmarked & we're about to remove single cell verification.
Here are the results from my system. I was a little surprised that `num_threads` didn't make a difference. Is that normal?
```
verify_cell_kzg_proof_batch - NUM_THREADS: 1
time:   [11.931 ms 11.954 ms 11.977 ms]
verify_cell_kzg_proof_batch - NUM_THREADS: 4
time:   [11.915 ms 11.951 ms 11.999 ms]
verify_cell_kzg_proof_batch - NUM_THREADS: 8
time:   [11.940 ms 11.965 ms 11.992 ms]
verify_cell_kzg_proof_batch - NUM_THREADS: 16
time:   [11.931 ms 11.958 ms 11.987 ms]
verify_cell_kzg_proof_batch - NUM_THREADS: 32
time:   [11.897 ms 11.920 ms 11.944 ms]
```

chore: convert benchmark for single cell verification to batch verification

---

bindings/java/rust_code/ethereum_cryptography_LibPeerDASKZG.h
eip7594/benches/benchmark.rs
eip7594/src/trusted_setup.rs
erasure_codes/src/reed_solomon.rs
kzg_multi_open/src/fk20/cosets.rs
kzg_multi_open/src/fk20/prover.rs
kzg_multi_open/src/fk20/verifier.rs

Primarily, this PR improves `compute_fiat_shamir_challenge` by making the `hash_input` definition more readable. I immediately wanted to do this, then I saw your TODO comment so I decided to do it. I haven't benchmarked it, but I really don't expect it to make any difference. Also added an assert at the bottom to ensure the size calculation is right.

chore: add correct Vector capacity to hash buffer in `compute_fiat_shamir_challenge`

---

bindings/c/src/blob_to_kzg_commitment.rs
bindings/c/src/compute_cells_and_kzg_proofs.rs
bindings/c/src/lib.rs
bindings/c/src/recover_cells_and_kzg_proofs.rs
bindings/c/src/verify_cells_and_kzg_proofs_batch.rs
bindings/csharp/csharp_code/PeerDASKZG.bindings/native_methods.g.cs
bindings/csharp/csharp_code/PeerDASKZG.bindings/peerdaskzg.cs
bindings/golang/prover.go
bindings/java/java_code/src/main/java/ethereum/cryptography/LibPeerDASKZG.java
bindings/java/rust_code/ethereum_cryptography_LibPeerDASKZG.h
bindings/java/rust_code/src/lib.rs
bindings/nim/nim_code/nim_peerdas_kzg/header.nim
bindings/nim/nim_code/nim_peerdas_kzg/nim_peerdas_kzg.nim
bindings/node/__test__/index.spec.ts
bindings/node/src/lib.rs
eip7594/benches/benchmark.rs
eip7594/src/lib.rs
eip7594/src/prover.rs
eip7594/src/verifier.rs
eip7594/tests/blob_to_kzg_commitment.rs
eip7594/tests/compute_cells_and_kzg_proofs.rs
eip7594/tests/recover_cells_and_compute_proofs.rs
eip7594/tests/verify_cell_kzg_proof_batch.rs

Pulled out from #89 
This library will include 4844 functions in the near future, so this premptively removes the PeerDAS prefic, for just DAS

chore: Rename PeerDASContext -> DASContext

---

bindings/java/rust_code/Cargo.toml

fix: `crate_type` -> `crate-type` warning

---

.cargo/config.node.cross.toml

We recently modified the node release workflow to no longer need this file

chore: remove unused cargo config file

---

.github/workflows/release-csharp-bindings.yml
.github/workflows/release-java-bindings.yml
.github/workflows/release-node-bindings.yml
.github/workflows/release-rust-crates.yml
.github/workflows/test-csharp-bindings.yml
.github/workflows/test-golang-bindings.yml
.github/workflows/test-nim-bindings.yml

chore: use stable rust everywhere with dtolnay github action

---

.cargo/config.cross.toml

For cross compilation, our CI has moved to using zig, so we no longer use the cross file for setting up the linker during cross compilation

chore: remove cross.toml file

---

eip7594/benches/benchmark.rs

Couldn't find anything wrong with this file, so just removed extra unused import

chore: cleanup eip7594 benchmarks file

---

bindings/c/src/lib.rs
bindings/csharp/csharp_code/EthKZG.bindings/ethkzg.cs
bindings/csharp/csharp_code/EthKZG.bindings/native_methods.g.cs
bindings/golang/prover.go
bindings/java/rust_code/src/lib.rs
bindings/nim/nim_code/nim_eth_kzg/header.nim
bindings/nim/nim_code/nim_eth_kzg/nim_eth_kzg.nim

fix: namespace C methods

---

.github/workflows/release-java-bindings.yml

I don't believe Python is needed, atleast not explicitly. Putting up this PR to remove it and see if it breaks anything.

chore: remove python from Java workflow

---

.github/workflows/release-node-bindings.yml

related to #172 
Adding ARM on windows will likely require quite a bit of time, since the runner for it is quite hard to work with.

chore: remove TODO re windows on ARM

---

eip7594/src/errors.rs
eip7594/src/prover.rs
eip7594/src/verifier.rs

This should never be hit, we leave it in since the decision on whether to switch to a vector has not been finalized yet.
It was added initially because cells used to be &[u8]

chore: change infallible error to an assert

---

bindings/node/__test__/index.spec.ts

This discrepancy only happens within tests, so this is okay to have

chore: remove TODO on discrepancy between number and bigint

---

cryptography/bls12_381/src/lib.rs

Before we were truncating off 2 bits and then we knew the value fit within a scalar. This is fine given we only need 128 bits.
We now change it to use the blst api to do the reduction, by converting to fr without checking for overflow.

chore: use blst methods to reduce a 32 byte hash to a scalar instead of rounding off the top 2 bits

---

cryptography/kzg_multi_open/src/fk20.rs
cryptography/kzg_multi_open/src/fk20/cosets.rs
cryptography/kzg_multi_open/src/fk20/prover.rs
cryptography/kzg_multi_open/src/lib.rs
eip7594/src/verifier.rs

Moves `recover_evaluations_in_domain_order` into cosets module, since it did not really have much to do with the prover

chore!: Move `recover_evaluations_in_domain_order` into cosets.rs

---

cryptography/kzg_multi_open/src/opening_key.rs

I don't think that this is needed, so removing the TODO

chore: remove todo pertaining to adding a protocol description structure

---

cryptography/kzg_multi_open/src/fk20/toeplitz.rs

This code is only called during tests, so whether it is generalized or not is insignificant

chore: Remove todo pertaining to generalizing `vector_mul`

---

cryptography/erasure_codes/src/reed_solomon.rs

The note is still useful, so its been added as a doc comment

chore: remove TODO in `acceptable_num_block_erasures`

---

eip7594/Cargo.toml

serde_yaml is only used in tests and is not broken, so we can remove the TODO that was added since it does not pose a threat

chore: remove serde_yaml deprecation notice

---

bindings/c/src/lib.rs
bindings/java/rust_code/Cargo.toml
bindings/java/rust_code/src/errors.rs
bindings/java/rust_code/src/lib.rs

This removes usage of rust-eth-kzg and officially only uses the c-eth-kzg API. I don't think it matters too much, which one of these we use out of rust-eth-kzg and c-eth-kzg

chore: Only use c-eth-kzg in java crate

---

bindings/csharp/rust_code/build.rs
bindings/java/rust_code/build.rs

The java build script is the only script to call a binary `javac` so its the only one we need to explicitly check for its status.
Ideally, we didn't need to do this and we could use some sort of library

chore: remove Java TODO in build script

---

cryptography/kzg_multi_open/src/fk20/verifier.rs

This at most costs 1ms, so removing todo and leaving the round trip here

chore: remove TODO regarding unecessary serialization of points 

---

bindings/c/src/pointer_utils.rs

We could possibly remove the need for this by passing the different reference arrays as slices, but this seems not completely necessary

chore: Remove TODO note on `write_to_2d_slice`

---

cryptography/kzg_multi_open/src/fk20/verifier.rs

rl is not a very descriptive name. I've changed it to `pairing_input_g1` which is also not great but its better than the status quo

chore: refactor `rl` variable

---

bindings/csharp/csharp_code/EthKZG.bindings/EthKZG.csproj
bindings/nim/nim_code/nim_eth_kzg.nimble

chore: standardize project descriptions for publish packages

---

bindings/c/src/recover_cells_and_kzg_proofs.rs
bindings/java/rust_code/src/lib.rs
bindings/node/src/lib.rs
eip7594/benches/benchmark.rs
eip7594/src/prover.rs
eip7594/tests/recover_cells_and_kzg_proofs.rs

Renaming so that it matches the specs

chore(rust)!: Rename `recover_cells_and_proofs` -> `recover_cells_and_kzg_proofs`

---

bindings/c/src/lib.rs
bindings/node/src/lib.rs
cryptography/bls12_381/benches/benchmark.rs
cryptography/bls12_381/src/fixed_base_msm.rs
cryptography/kzg_multi_open/benches/benchmark.rs
cryptography/kzg_multi_open/src/fk20/batch_toeplitz.rs
cryptography/kzg_multi_open/src/fk20/h_poly.rs
cryptography/kzg_multi_open/src/fk20/prover.rs
eip7594/benches/benchmark.rs
eip7594/src/constants.rs
eip7594/src/lib.rs
eip7594/src/prover.rs

**Breaking change**
Users now need to specify whether they want to use Precomp or not, if calling DasContext::with_threads. To preserve the previous behaviour, one can pass `UsePrecomp::Yes{width:8}`
Its also breaking because the `Default::default` method no longer creates the precomputations. This was changed because the Default::default method was using up 100MB of data, and we want the user to intentionally opt into this.
**Note**
In the future, we may be able to allow the user to specify a memory-limit and we compute the width parameter based off of that, but this seems like a non-goal right now

feat!: Allow downstream users to avoid the precomputations that are needed for the FixedBaseMSM algorithm in FK20

---

bindings/c/src/lib.rs
bindings/node/src/lib.rs
eip7594/benches/benchmark.rs
eip7594/src/lib.rs

**Breaking change**
Instead of specifying the number of threads with a usize like `5`, users can now specify it by doing `ThreadCount::Multi(5)`

feat!: Add a ThreadCount enum for specifying the number of threads to use

---

bindings/java/java_code/src/main/java/ethereum/cryptography/CellsAndProofs.java
bindings/java/java_code/src/main/java/ethereum/cryptography/LibEthKZG.java

These are only needed to make javadoc happy, I don't think creating significant docs for the bindings is worth it since they will need to be repeated for every binding.

chore: Add redundant java docs

---

cryptography/bls12_381/Cargo.toml

chore: Codify subtle version that rust-eth-kzg works with as >=2.5.0

---

cryptography/bls12_381/Cargo.toml
cryptography/bls12_381/src/batch_inversion.rs

There was no measurable difference between single and multithreaded for our usecases

chore: Make batch_inverse single threaded

---

cryptography/bls12_381/benches/benchmark.rs
cryptography/bls12_381/src/booth_encoding.rs
cryptography/bls12_381/src/fixed_base_msm.rs
cryptography/bls12_381/src/fixed_base_msm_window.rs
cryptography/bls12_381/src/lib.rs

This has been pulled out of #267 
We implement the same strategy that blst implements with the caveat that we use the somewhat novel but trivial multi-batch-addition. This results in roughly a 40% performance increase over the blst method.

feat: Replace blst msm method with a Rust native method

---

eip7594/Cargo.toml

The benchmarks as written currently require the multithreaded feature flag, so we specify this in Cargo.toml.
If not specified, then it will just give an error when compiling, due to some features being under the multithreaded feature flag.

chore: enable required features for benchmarks

---

cryptography/erasure_codes/src/reed_solomon.rs
cryptography/kzg_multi_open/benches/benchmark.rs
cryptography/kzg_multi_open/src/fk20/cosets.rs
cryptography/kzg_multi_open/src/fk20/h_poly.rs
cryptography/kzg_multi_open/src/fk20/toeplitz.rs
cryptography/kzg_multi_open/src/fk20/verifier.rs
cryptography/kzg_multi_open/src/lib.rs
cryptography/kzg_multi_open/src/naive.rs
cryptography/polynomial/src/domain.rs
cryptography/polynomial/src/monomial.rs

closes #264 
There are some places where it is left in (mainly tests) just due to the code needing to do things like : `vec![Scalar::from(0), Scalar::from(1), Scalar::from(2)]`
The main downside of Scalar::ONE and Scalar::ZERO is that they require another import but I think its fine for the most part since we usually already import ff::Field for other methods

chore: replace Scalar::from(0u64) and Scalar::from(1u64)

---

cryptography/kzg_multi_open/benches/benchmark.rs
cryptography/kzg_multi_open/src/fk20/h_poly.rs
cryptography/kzg_multi_open/src/fk20/prover.rs
cryptography/kzg_multi_open/src/fk20/verifier.rs
cryptography/kzg_multi_open/src/lib.rs
cryptography/kzg_multi_open/src/naive.rs
cryptography/kzg_multi_open/src/verification_key.rs
eip7594/src/trusted_setup.rs
eip7594/src/verifier.rs

chore: rename `opening_key` to `verification_key`

---

cryptography/kzg_multi_open/src/fk20/verifier.rs

chore: rename `s` to `tau` for trusted setup secret

---

eip7594/src/errors.rs
eip7594/src/lib.rs
eip7594/src/prover.rs
eip7594/src/recovery.rs
eip7594/src/verifier.rs

chore: move recovery code to its own module

---

cryptography/polynomial/src/domain.rs

chore: add a FFT trait to deduplicate FFT code

---

.github/scripts/install_libnode_dll_windows.sh
.github/workflows/release-csharp-bindings.yml
.github/workflows/release-java-bindings.yml
.github/workflows/release-rust-crates.yml
.github/workflows/test-golang-bindings.yml
.github/workflows/test-nim-bindings.yml
bindings/node/Cargo.toml
bindings/node/package.json

Windows builds are failing because napi-build is looking for libnode.dll, however this does not come with distributed binaries, hence it is failing to find it on the system.
Here, we just fetch it from a released repo that precompiles them

chore: Fix windows build

---

cryptography/kzg_multi_open/src/fk20/prover.rs
eip7594/src/prover.rs
eip7594/src/serialization.rs
eip7594/tests/compute_cells_and_kzg_proofs.rs

Adds back the method to extend blobs -- this was recently added back into the specs

feat(rust-eth-kzg): add `compute_cells`

---

cryptography/bls12_381/Cargo.toml
cryptography/kzg_multi_open/Cargo.toml
cryptography/kzg_multi_open/src/fk20/batch_toeplitz.rs
cryptography/kzg_multi_open/src/fk20/h_poly.rs
cryptography/kzg_multi_open/src/fk20/prover.rs
cryptography/polynomial/Cargo.toml
cryptography/polynomial/src/domain.rs
eip7594/Cargo.toml
eip7594/examples/compute_cells_and_kzg_proof.rs
eip7594/src/prover.rs

- Add dep `tracing` to `bls12_381`, `kzg_multi_open`, `polynomial` and `eip7594`
- Add a example `compute_cells_and_kzg_proof` to show the runtime breakdown
Running `cargo run --release --features multithreaded,tracing --example compute_cells_and_kzg_proof` we will get something like:

feat: Add `tracing` deps and trace time-consuming functions

---

cryptography/bls12_381/Cargo.toml

We can add this back under the multithreaded flag and remove the thread control parameter

chore: disable blst multithreading

---

cryptography/erasure_codes/Cargo.toml
cryptography/polynomial/Cargo.toml
cryptography/polynomial/src/domain.rs
cryptography/polynomial/src/fft.rs
eip7594/examples/compute_cells_and_kzg_proof.rs
maybe_rayon/src/multi_threaded.rs
maybe_rayon/src/single_threaded.rs

Adopt cache-aware radix-2 fft from Plonky3 https://github.com/Plonky3/Plonky3/blob/a374139/dft/src/radix_2_dit_parallel.rs#L106, but it requires pre-computed twiddles in bit-reversed order, which doubles the memory requirement of `Domain`. If we find this unacceptable for verifier, we could opt-out it for verifier.
Before:
```
INFO     compute_cells_and_kzg_proofs [ 45.0ms | 0.50% / 100.00% ]
INFO     ┝━ ifft_scalars [ 905µs | 2.01% ]
INFO     ┕━ compute_multi_opening_proofs_poly_coeff [ 43.9ms | 0.07% / 97.49% ]
INFO        ┝━ compute_h_poly_commitments [ 25.4ms | 0.71% / 56.36% ]
INFO        │  ┝━ compute fixed-base msm on matrix-vec-mul result [ 5.23ms | 11.62% ]
INFO        │  ┕━ ifft_g1_take_n [ 19.8ms | 44.04% ]
INFO        ┝━ compute proof from h_poly_commitments [ 16.6ms | 0.00% / …
```

feat: adopt cache-aware radix-2 fft from Plonky3

---

cryptography/bls12_381/src/batch_addition.rs

It slowdowns the overall fixed-base msm by 1ms in singlethreaded setting.
We can make the function complete by adding `points.retain(|point| !bool::from(point.is_identity()));` in the beginning of each iteration, but the slowdown will becomes 3ms.

feat: add non-identity checks and panics docs for batch-add methods

---

Cargo.toml
crates/cryptography/bls12_381/Cargo.toml
crates/cryptography/kzg_multi_open/Cargo.toml
crates/cryptography/polynomial/Cargo.toml
crates/eip4844/Cargo.toml
crates/eip4844/examples/compute_kzg_proof.rs
crates/eip4844/src/constants.rs
crates/eip4844/src/cryptography.rs
crates/eip4844/src/errors.rs
crates/eip4844/src/lib.rs
crates/eip4844/src/prover.rs
crates/eip4844/src/serialization.rs
crates/eip4844/src/trusted_setup.rs
crates/eip4844/src/verifier.rs
crates/eip4844/tests/blob_to_kzg_commitment.rs
crates/eip4844/tests/common.rs
crates/eip4844/tests/compute_blob_kzg_proof.rs
crates/eip4844/tests/compute_kzg_proof.rs
crates/eip4844/tests/verify_blob_kzg_proof.rs
crates/eip4844/tests/verify_blob_kzg_proof_batch.rs
crates/eip4844/tests/verify_kzg_proof.rs
crates/eip7594/Cargo.toml
crates/eip7594/src/trusted_setup.rs

Adding EIP4844 APIs and tests.
Now it uses very ugly way to get the constant, method and structures of  `constants.rs`, `serialization.rs` and `trusted_setup.rs` in crate `eip7594`, it'd be much better to refactor these common utilities into another crate for reuse.

feat: add crate `eip4844` and the corresponding APIs and tests

---

crates/cryptography/kzg_multi_open/src/fk20/verifier.rs
crates/eip7594/src/errors.rs
crates/eip7594/src/lib.rs
crates/eip7594/src/recovery.rs

- The logic of `find_missing_cell_indices` seemed to be very simple and only used at one place so I just moved the logic there to rm the function.
- Header doc is added to the functions to better explain their utility.
- The `validation` module is removed with a more descriptive name for `validate_recovery_inputs` in order to avoid same naming with `rs.recover_polynomial_coefficient`
- Unit tests are added to check some validation cases.

chore: small reorg of eip7594 recovery and unit tests

---

crates/eip4844/src/kzg_open.rs
crates/eip4844/src/prover.rs
crates/eip4844/src/verifier.rs

- Rework `compute_evaluation_and_quotient` to `divide_by_linear` base on https://github.com/crate-crypto/rust-eth-kzg/pull/362#discussion_r2077938243
- Use u128 to serialize polynomial bound in Fiat-Shamir to make it less confusing

feat: addressing review of `eip4844` in #362

---

crates/cryptography/polynomial/src/domain.rs
crates/cryptography/polynomial/src/fft.rs

@kevaundray As `fft_g1_inplace` and `fft_scalar_inplace` shared exactly the same logic, they are removed to expose directly `fft_inplace` and simplify the usage from a user perspective. Let me know what you think about this?

chore: unify `fft_inplace`

---

crates/cryptography/kzg_multi_open/src/fk20/batch_toeplitz.rs
crates/cryptography/kzg_multi_open/src/fk20/toeplitz.rs

A check is added to verify that during the construction of `ToeplitzMatrix`, `col[0] == row[0]` with an associated unit test to protect this behaviour.

chore: add unit test and check for `ToeplitzMatrix`

---

crates/eip4844/src/trusted_setup.rs

To maintain homogeneity with what we have here: https://github.com/crate-crypto/rust-eth-kzg/blob/master/crates/eip7594/src/trusted_setup.rs

chore: refactor serialization methods for eip 4844

---

bindings/c/src/lib.rs
bindings/java/rust_code/src/lib.rs
bindings/node/src/lib.rs
crates/eip7594/src/errors.rs
crates/eip7594/tests/verify_cell_kzg_proof_batch.rs

To be more descriptive with what the function is doing.

chore: rename `invalid_proof` to `is_fk20_verification_failure`

---

bindings/node/index.d.ts
bindings/node/src/lib.rs

Motivation:
- In practice, indices are quite small and don't need to be bigint
- It's convenient (and more performant) to use number when indices are small
Description:
- Convert functions with `Vec<BigInt>` params to `Vec<Either<u32, BigInt>>`
- Convert `bigint_to_u64` to `u32_or_bigint_to_u64`

feat(nodejs): support number or bigint input

---

crates/cryptography/kzg_multi_open/src/fk20/verifier.rs

chore: add assertion that cosets are the same size

---

crates/cryptography/bls12_381/Cargo.toml
crates/cryptography/bls12_381/src/lincomb.rs

We had an issue where blst was not correctly treating the identity point -- this should have been fixed as of 0.3.16 but we are adding this defensive assert code here anyways

chore: filter out identity points in blst msm
