.github/workflows/test-nim-bindings.yml

#23 is experimenting with msvc while this experiments with gnu

chore: add back nim for windows (mingw)

---

kzg_multi_open/src/fk20/h_poly.rs

chore: remove usage of `l`

---

README.md
eip7594/src/constants.rs
eip7594/src/serialization.rs
eip7594/src/trusted_setup.rs
kzg_multi_open/src/fk20/prover.rs

This PR fixes a few small nits I've noticed.

fix: small nits

---

release-please-config.json

Adds the erasure codes path, so that its version gets updated

fix: add erasure codes path to release-please-config.json

---

.github/workflows/release-java-bindings.yml

chore: use java 11 instead of java 17 in tests

---

cryptography/kzg_multi_open/src/fk20.rs
cryptography/kzg_multi_open/src/fk20/errors.rs
cryptography/kzg_multi_open/src/fk20/prover.rs
cryptography/kzg_multi_open/src/fk20/verifier.rs
cryptography/kzg_multi_open/src/lib.rs
eip7594/src/errors.rs
eip7594/src/verifier.rs

This cleans up the verifier code and returns an enum versus a boolean

chore: cleanup and add more docs on the verification code

---

cryptography/kzg_multi_open/src/fk20/verifier.rs

chore: update docs on FK20 naming

---

eip7594/src/lib.rs

chore: remove TODO regard changing blob/Cell to be  Vec<u8>

---

cryptography/bls12_381/src/lib.rs

chore: remove TODO for `batch_normalize_points`

---

bindings/nim/nim_code/nim_eth_kzg/nim_eth_kzg.nim

chore: remove TODO pertaining nim error pointer

---

bindings/nim/nim_code/nim_eth_kzg/nim_eth_kzg.nim

chore: Free nim error message after copying it

---

cryptography/bls12_381/benches/benchmark.rs

chore: Remove the ability to initialize a vector by copying in the first element only

---

cryptography/kzg_multi_open/src/fk20/cosets.rs

chore: Elaborate on what is meant by "domain order"

---

bindings/c/src/lib.rs
bindings/csharp/csharp_code/EthKZG.bindings/ethkzg.cs
bindings/csharp/csharp_code/EthKZG.bindings/native_methods.g.cs
bindings/golang/prover.go
bindings/java/java_code/src/main/java/ethereum/cryptography/LibEthKZG.java
bindings/java/rust_code/ethereum_cryptography_LibEthKZG.h
bindings/java/rust_code/src/lib.rs
bindings/nim/nim_code/nim_eth_kzg/header.nim
bindings/nim/nim_code/nim_eth_kzg/nim_eth_kzg.nim
bindings/node/index.d.ts
bindings/node/src/lib.rs

feat: Allow bindings to specify the number of threads and whether precomputation is wanted

---

.github/workflows/release-csharp-bindings.yml
.github/workflows/release-java-bindings.yml
.github/workflows/release-node-bindings.yml
.github/workflows/release-rust-crates.yml
.github/workflows/test-golang-bindings.yml
.github/workflows/test-nim-bindings.yml
scripts/compile.sh

See #269 
This only affects cross compilation, you can run any version of Rust locally

feat: Pin Rust CI to 1.80.0

---

cryptography/bls12_381/src/batch_add.rs
cryptography/bls12_381/src/lib.rs

chore: add `batch_addition` code

---

cryptography/polynomial/src/domain.rs

chore: use iterative version of fft code

---

cryptography/bls12_381/src/batch_addition.rs
cryptography/bls12_381/src/fixed_base_msm_window.rs
cryptography/bls12_381/src/lib.rs

chore: rename batch_add -> batch_addition

---

cryptography/polynomial/src/domain.rs

chore: rename mention of DFT to FFT

---

cryptography/kzg_multi_open/src/naive.rs

chore: standardize on using I(x) for interpolation polynomial

---

eip7594/src/verifier.rs

chore: add comment on redundant check being done in recover_polynomial_coeff

---

cryptography/polynomial/src/domain.rs
cryptography/polynomial/src/fft.rs
cryptography/polynomial/src/lib.rs

chore: move FFT code into fft module

---

cryptography/bls12_381/src/lib.rs

This optimizes the batch normalization function, to amortize the cost of inversion across multiple points

feat: Optimize batch normalisation

---

crates/eip4844/src/trusted_setup.rs
crates/eip7594/src/trusted_setup.rs

@kevaundray Small touchup to avoid 48 hardcoded in the code :)

chore: rm some hardcoded 48

---

crates/eip7594/examples/compute_cells_and_kzg_proof.rs

@kevaundray As it is an example, I thought that maybe a header doc for the file and step-by-step documentation would be welcome for the user to be able to check the steps. We can probably do something even more detailed but this seems to be a good start.

chore: add more doc to eip7594 example

---

crates/eip4844/src/trusted_setup.rs

Resolves https://github.com/crate-crypto/rust-eth-kzg/issues/355

feat: Validate points in trusted setup

---

.github/workflows/clippy.yml
crates/eip4844/src/lib.rs
crates/eip7594/benches/benchmark-st.rs
crates/eip7594/src/lib.rs

chore: fix clippy
